# Generated by Django 4.0.5 on 2022-10-26 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='soccer',
            name='salary',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
