# Generated by Django 4.0.5 on 2022-11-01 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0002_soccer_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='soccer',
            name='incentive',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
